name: 'Bikeclub Page'
description: 'Provides Basic Page content type.'
type: 'Content type'
recipes:
  - bikeclub_banner
  - bikeclub_content_type_base
config:
  strict: false
  actions:
    user.role.site_admin:
      createIfNotExists:
        label: 'Site administrator'
      grantPermissions:
        - 'create page content'
        - 'delete any page content'
        - 'edit any page content'
        - 'use text format basic_html'
        - 'use text format summary_fields'
    view.view.content:  
      addItemToDisplayOption:
        display_id: 'page_1'
        option: filters
        field_page_access_target_id:
        settings:
          id: field_page_access_target_id
          table: node__field_page_access
          field: field_page_access_target_id
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: taxonomy_index_tid
          operator: or
          value: {  }
          group: 1
          exposed: true
          expose:
            operator_id: field_page_access_target_id_op
            label: 'Access restricted to'
            description: ''
            use_operator: false
            operator: field_page_access_target_id_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: field_page_access_target_id
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          reduce_duplicates: false
          vid: page_access
          type: select
          hierarchy: false
          limit: true
          error_message: true