name: 'Bikeclub Page'
description: 'Provides Basic Page content type.'
type: 'Content type'
recipes:
  - bikeclub_banner
  - bikeclub_content_type_base
config:
  strict: false
  actions:
    user.role.site_admin:
      createIfNotExists:
        label: 'Site administrator'
      grantPermissions:
        - 'create page content'
        - 'delete any page content'
        - 'edit any page content'
        - 'use text format basic_html'
        - 'use text format summary_fields'
